name: "aiad-web"
version: "0.0.1"
author: "Niklas Rosenstein <rosensteinniklas@gmail.com>"
license: "MIT"
description: "Web API and page for An Image a Day."
requirements:
  - python ^3.4
  - flask ^1.1.2
  - nr.databind.rest 0.0.1
  - pyyaml
