name: "aiad-cli"
version: "0.0.1"
author: "Niklas Rosenstein <rosensteinniklas@gmail.com>"
license: "MIT"
description: "CLI to manage the An Image a Day Wallpaper database."
requirements:
  - python ^3.4
  - beautifulsoup4 ^4.9.1
  - click ^7.1.2
  - nr.databind.core ~0.0.14
  - nr.databind.json ~0.0.9
  - nr.interface ~0.0.2
  - nr.proxy ~0.0.2
  - requests ^2.23.0
  - termcolor ^1.1.0
entrypoints:
  aiad_cli.resolvers:
    - pexels = aiad_cli.resolvers.pexels:PexelsWallpaperSpecResolver
    - unsplash = aiad_cli.resolvers.unsplash:UnsplashWallpaperSpecResolver
    - wallpapershome = aiad_cli.resolvers.wallpapershome:WallpapersHomeSpecResolver
  console_scripts:
    - aiad-cli = aiad_cli.__main__:cli
