# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: On Pull Request

on:
  pull_request:
    branches: [ master ]

jobs:
  validate-wallpapers:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.5
      uses: actions/setup-python@v2
      with:
        python-version: 3.5
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pushd aiad-ci && pip install -r requirements.txt && popd
    - name: Validate Wallpaper Specs
      run: |
        git fetch
        git checkout master
        git checkout $GITHUB_HEAD_REF
        git diff --name-only $GITHUB_BASE_REF..$GITHUB_HEAD_REF
        python aiad-ci/validate-wallpapers.py $GITHUB_BASE_REF..$GITHUB_HEAD_REF
