name: On Push

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  render-gh-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.5
      uses: actions/setup-python@v2
      with:
        python-version: 3.5
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pushd aiad-ci && pip install -r requirements.txt && popd
    - name: Render channels HTML page
      run: |
        git checkout --orphan gh-pages
        python aiad-ci/render-channel-html-page.py >index.html
        git add index.html
        git push origin gh-pages --force
